version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./hf_cache:/hf_cache
    environment:
      - OPENAI_API_KEY= ${OPENAI_API_KEY:-}
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - chatapp-network
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]  # Specify ASGI app import here


  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: chat_app_db
      POSTGRES_USER: chat_app_user
      POSTGRES_PASSWORD: chat_app_password
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge

volumes:
  pg_data:
